name: Things
description: An AI-powered LifeOS app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  geolocator: ^13.0.0
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  # Core
  provider: ^6.0.0
  http: ^1.2.0
  uuid: ^4.0.0
  intl: ^0.20.2
  path_provider: ^2.1.2
  share_plus: ^12.0.1
  url_launcher: ^6.2.4

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  flex_color_picker: ^3.4.0
  table_calendar: ^3.0.9
  
  # Editor & Utils
  flutter_quill: ^11.5.0
  flutter_quill_extensions: ^11.0.0
  image_picker: ^1.0.7
  hand_signature: ^3.0.0

  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.5.4
  flutter_dotenv: ^6.0.0
  matrix_gesture_detector: ^0.2.0-nullsafety.1
  permission_handler: ^12.0.1

  # Audio
  just_audio: ^0.9.36

  # Maps (OpenStreetMap implementation)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env